Update

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -1,21 +1,24 @@
-commonStep: &generate_sdks_and_pull_request
-  name: Generate SDKs and Pull Request
-  image: node:20
-  caches:
-    - node
-  script:
-    - |
-      if [ -z "$LIBLAB_TOKEN" ] || [ -z "$LIBLAB_GITLAB_TOKEN" ]; then
-        echo "Error: Variables LIBLAB_TOKEN and LIBLAB_GITLAB_TOKEN are required, see https://developers.liblab.com/tutorials/integrate-with-gitlab-actions/#create-tokens"
-        exit 1
-    - npm install -g liblab
-    - liblab build --yes --pr -p bitbucket
-  condition:
-    changes:
-      - "liblab.config.json"
-      - "spec/*"
-      - "hooks/**"
-      - "customPlanModifiers/**"
+definitions:
+  steps:
+    - step: &generate_sdks_and_pull_request
+        name: Generate SDKs and Pull Request
+        image: node:20
+        caches:
+          - node
+        script:
+          - |
+            # Check for changes in the specified files or directories
+            if git diff --quiet HEAD~1 -- liblab.config.json spec/ hooks/ customPlanModifiers/; then
+              echo "No changes detected in relevant files. Skipping step."
+              exit 0
+            fi
+          - |
+            if [ -z "$LIBLAB_TOKEN" ] || [ -z "$LIBLAB_GITLAB_TOKEN" ]; then
+              echo "Error: Variables LIBLAB_TOKEN and LIBLAB_GITLAB_TOKEN are required, see https://developers.liblab.com/tutorials/integrate-with-gitlab-actions/#create-tokens"
+              exit 1
+            fi
+          - npm install -g liblab
+          - liblab build --yes --pr -p bitbucket
 
 pipelines:
   branches:
@@ -25,7 +28,3 @@ pipelines:
   pull-requests:
     '**':
       - step: *generate_sdks_and_pull_request
-
-definitions:
-  caches:
-    node: ~/.npm
